version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - erota
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'"
    command: certonly --webroot -w /var/www/certbot -d api.vecna.online --agree-tos --email your-email@example.com --non-interactive

  erota:
    image: vikasdev4046/erota:1.0
    container_name: erota_app
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env

  certbot-renew:
    image: certbot/certbot:latest
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew && nginx -s reload; done'"
    restart: unless-stopped